/**
 * Attestation utilities — re-exports from shared attestation module.
 * This file exists so the fund manager can import attestation functions
 * without a cross-project dependency. The logic mirrors guardian-network's
 * shared/attestation.ts and will be unified when we set up a shared package.
 */
import { createHash, randomBytes } from 'node:crypto';

/** Attestation document generated by the TEE. */
export interface Attestation {
  teeInstanceId: string;
  codeHash: string;
  timestamp: number;
  nonce: string;
  signature: string;
}

export function generateAttestation(
  teeInstanceId: string,
  codeHash: string,
  signingSecret?: string,
): Attestation {
  const timestamp = Date.now();
  const nonce = randomBytes(16).toString('hex');
  const message = `${teeInstanceId}|${codeHash}|${timestamp}|${nonce}`;
  const secret = signingSecret ?? 'dev-attestation-secret';
  const signature = createHash('sha256')
    .update(`${secret}:${message}`)
    .digest('hex');

  return { teeInstanceId, codeHash, timestamp, nonce, signature };
}

export function serializeAttestation(attestation: Attestation): string {
  return Buffer.from(JSON.stringify(attestation)).toString('base64');
}

export function deserializeAttestation(encoded: string): Attestation {
  return JSON.parse(Buffer.from(encoded, 'base64').toString('utf-8')) as Attestation;
}
