/**
 * TEE Attestation utilities — shared between fund manager and guardian.
 *
 * Attestation proves:
 *   1. The code running (codeHash)
 *   2. The hardware it's running on (teeInstanceId)
 *   3. When it was generated (timestamp)
 *
 * On Intel TDX (SecretVM), attestations are signed by the CPU and can be
 * verified against Intel's root of trust. This module provides the
 * generation and verification interface.
 */
import { createHash, randomBytes } from 'node:crypto';

/** Attestation document generated by the TEE. */
export interface Attestation {
  /** Unique TEE hardware instance ID. */
  teeInstanceId: string;
  /** SHA-256 hash of the running code/container. */
  codeHash: string;
  /** Unix timestamp (ms) when attestation was generated. */
  timestamp: number;
  /** Nonce to prevent replay attacks. */
  nonce: string;
  /** Signature over the above fields (from TEE hardware or HMAC in dev). */
  signature: string;
}

/** Parsed and verified attestation result. */
export interface VerificationResult {
  valid: boolean;
  teeInstanceId: string;
  codeHash: string;
  timestamp: number;
  /** Seconds since attestation was generated. */
  ageSeconds: number;
  error?: string;
}

/**
 * Generate a SHA-256 hash of the given content.
 * Used to compute code hashes from Docker image contents or source bundles.
 */
export function computeCodeHash(content: string | Buffer): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Generate an attestation document.
 *
 * In production (Intel TDX), this reads MRTD/RTMR registers and gets a
 * hardware-signed quote. In development, it uses HMAC signing with a
 * local secret.
 */
export function generateAttestation(
  teeInstanceId: string,
  codeHash: string,
  signingSecret?: string,
): Attestation {
  const timestamp = Date.now();
  const nonce = randomBytes(16).toString('hex');

  // Create the message to sign
  const message = `${teeInstanceId}|${codeHash}|${timestamp}|${nonce}`;

  // In dev mode, use HMAC. In production, this would be a TDX quote.
  const secret = signingSecret ?? 'dev-attestation-secret';
  const signature = createHash('sha256')
    .update(`${secret}:${message}`)
    .digest('hex');

  return {
    teeInstanceId,
    codeHash,
    timestamp,
    nonce,
    signature,
  };
}

/**
 * Verify an attestation document.
 *
 * In production, this verifies the Intel TDX signature chain.
 * In development, it verifies the HMAC.
 */
export function verifyAttestation(
  attestation: Attestation,
  options?: {
    /** Expected code hash (reject if mismatch). */
    expectedCodeHash?: string;
    /** Max age in seconds (reject if too old). */
    maxAgeSeconds?: number;
    /** Signing secret for dev verification. */
    signingSecret?: string;
  },
): VerificationResult {
  const now = Date.now();
  const ageSeconds = Math.floor((now - attestation.timestamp) / 1000);

  const base: VerificationResult = {
    valid: false,
    teeInstanceId: attestation.teeInstanceId,
    codeHash: attestation.codeHash,
    timestamp: attestation.timestamp,
    ageSeconds,
  };

  // Check age (use != null so maxAgeSeconds: 0 is respected)
  if (options?.maxAgeSeconds != null && ageSeconds >= options.maxAgeSeconds) {
    return { ...base, error: `Attestation too old: ${ageSeconds}s >= ${options.maxAgeSeconds}s` };
  }

  // Check code hash
  if (options?.expectedCodeHash && attestation.codeHash !== options.expectedCodeHash) {
    return {
      ...base,
      error: `Code hash mismatch: expected ${options.expectedCodeHash}, got ${attestation.codeHash}`,
    };
  }

  // Verify signature
  const message = `${attestation.teeInstanceId}|${attestation.codeHash}|${attestation.timestamp}|${attestation.nonce}`;
  const secret = options?.signingSecret ?? 'dev-attestation-secret';
  const expectedSig = createHash('sha256')
    .update(`${secret}:${message}`)
    .digest('hex');

  if (attestation.signature !== expectedSig) {
    return { ...base, error: 'Invalid signature' };
  }

  return { ...base, valid: true };
}

/**
 * Serialize an attestation to a compact string for transmission.
 */
export function serializeAttestation(attestation: Attestation): string {
  return Buffer.from(JSON.stringify(attestation)).toString('base64');
}

/**
 * Deserialize an attestation from a compact string.
 */
export function deserializeAttestation(encoded: string): Attestation {
  return JSON.parse(Buffer.from(encoded, 'base64').toString('utf-8')) as Attestation;
}
